"""
Temporal graph representation.
Maintains events as nodes and temporal relations as labeled directed edges,
supporting path finding, relation queries, and graph export.
"""

from __future__ import annotations
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Set, Tuple, Union
from collections import deque

from temporal_reasoning.events import Event
from temporal_reasoning.relations import TemporalRelation, get_inverse


@dataclass(frozen=True)
class TemporalEdge:
    """
    A directed edge representing a temporal relation between two events.

    Attributes:
        source_id: Origin event ID.
        target_id: Destination event ID.
        relation: TemporalRelation.
        is_inferred: True if generated by the inference engine, False if explicitly stated.
        confidence: Confidence score in range [0.0, 1.0].
        provenance: Description of rule or path that produced this edge.
    """

    source_id: str
    target_id: str
    relation: TemporalRelation
    is_inferred: bool = False
    confidence: float = 1.0
    provenance: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "source_id": self.source_id,
            "target_id": self.target_id,
            "relation": self.relation.value,
            "is_inferred": self.is_inferred,
            "confidence": self.confidence,
            "provenance": self.provenance,
        }


class TemporalGraph:
    """
    Directed temporal graph structure.
    Nodes are Event instances, edges are TemporalEdge instances.
    """

    def __init__(self):
        self._events: Dict[str, Event] = {}
        # Map lowercased description to event_id for natural lookup
        self._name_to_id: Dict[str, str] = {}
        # (source_id, target_id) -> list of TemporalEdge
        self._adjacency: Dict[str, Dict[str, List[TemporalEdge]]] = {}

    @property
    def events(self) -> Dict[str, Event]:
        return dict(self._events)

    def add_event(self, event: Event) -> None:
        """Add an event node to the graph."""
        self._events[event.event_id] = event
        self._name_to_id[event.description.strip().lower()] = event.event_id
        if event.event_id not in self._adjacency:
            self._adjacency[event.event_id] = {}

    def get_event(self, identifier: str) -> Optional[Event]:
        """Look up an event by event_id or description."""
        if identifier in self._events:
            return self._events[identifier]
        key = identifier.strip().lower()
        if key in self._name_to_id:
            return self._events[self._name_to_id[key]]
        return None

    def _resolve_id(self, item: Union[str, Event]) -> str:
        if isinstance(item, Event):
            return item.event_id
        ev = self.get_event(item)
        if ev:
            return ev.event_id
        return item

    def add_relation(
        self,
        source: Union[str, Event],
        target: Union[str, Event],
        relation: TemporalRelation,
        is_inferred: bool = False,
        confidence: float = 1.0,
        provenance: Optional[str] = None,
    ) -> TemporalEdge:
        """Add a directed temporal relation edge between two events."""
        src_id = self._resolve_id(source)
        tgt_id = self._resolve_id(target)

        # Ensure events exist in graph
        if src_id not in self._events:
            ev_desc = source if isinstance(source, str) else src_id
            self.add_event(Event(event_id=src_id, description=ev_desc))
        if tgt_id not in self._events:
            ev_desc = target if isinstance(target, str) else tgt_id
            self.add_event(Event(event_id=tgt_id, description=ev_desc))

        edge = TemporalEdge(
            source_id=src_id,
            target_id=tgt_id,
            relation=relation,
            is_inferred=is_inferred,
            confidence=confidence,
            provenance=provenance or ("inferred" if is_inferred else "explicit"),
        )

        neighbors = self._adjacency.setdefault(src_id, {})
        edge_list = neighbors.setdefault(tgt_id, [])

        # Deduplicate identical relations
        existing = [e for e in edge_list if e.relation == relation]
        if existing:
            return existing[0]

        edge_list.append(edge)
        return edge

    def get_relations_between(
        self,
        source: Union[str, Event],
        target: Union[str, Event],
    ) -> Set[TemporalRelation]:
        """Return the set of temporal relations asserted from source to target."""
        src_id = self._resolve_id(source)
        tgt_id = self._resolve_id(target)
        if src_id in self._adjacency and tgt_id in self._adjacency[src_id]:
            return {e.relation for e in self._adjacency[src_id][tgt_id]}
        return set()

    def get_relation(
        self,
        source: Union[str, Event],
        target: Union[str, Event],
    ) -> Optional[TemporalRelation]:
        """Return a primary temporal relation between source and target if one exists."""
        rels = self.get_relations_between(source, target)
        if rels:
            # Return explicit relation first if available
            src_id = self._resolve_id(source)
            tgt_id = self._resolve_id(target)
            edges = self._adjacency.get(src_id, {}).get(tgt_id, [])
            explicit = [e.relation for e in edges if not e.is_inferred]
            if explicit:
                return explicit[0]
            return next(iter(rels))
        return None

    def get_all_edges(self) -> List[TemporalEdge]:
        """Return all edges in the graph."""
        all_edges: List[TemporalEdge] = []
        for src, targets in self._adjacency.items():
            for tgt, edges in targets.items():
                all_edges.extend(edges)
        return all_edges

    def find_path(
        self,
        source: Union[str, Event],
        target: Union[str, Event],
    ) -> Optional[List[TemporalEdge]]:
        """Find a directed relation path between source and target using BFS."""
        src_id = self._resolve_id(source)
        tgt_id = self._resolve_id(target)

        if src_id not in self._adjacency or tgt_id not in self._events:
            return None
        if src_id == tgt_id:
            return []

        queue = deque([(src_id, [])])
        visited = {src_id}

        while queue:
            curr, path = queue.popleft()
            if curr == tgt_id:
                return path

            for next_node, edges in self._adjacency.get(curr, {}).items():
                if next_node not in visited and edges:
                    visited.add(next_node)
                    # Use first available edge along this hop
                    queue.append((next_node, path + [edges[0]]))

        return None

    def detect_direct_contradictions(self) -> List[Dict[str, Any]]:
        """
        Detect obvious conflicting relation edges between the same pair of nodes.
        e.g., both BEFORE and AFTER asserted directly between A and B.
        """
        contradictions = []
        for src_id, targets in self._adjacency.items():
            for tgt_id, edges in targets.items():
                if src_id == tgt_id:
                    for e in edges:
                        if e.relation in (TemporalRelation.BEFORE, TemporalRelation.AFTER):
                            contradictions.append({
                                "type": "self_loop_conflict",
                                "source": src_id,
                                "relation": e.relation.value,
                                "message": f"Event {src_id} cannot be {e.relation.value} itself",
                            })
                rels = {e.relation for e in edges}
                if TemporalRelation.BEFORE in rels and TemporalRelation.AFTER in rels:
                    contradictions.append({
                        "type": "direct_relation_conflict",
                        "source": src_id,
                        "target": tgt_id,
                        "relations": [r.value for r in rels],
                        "message": f"Events {src_id} and {tgt_id} have conflicting relations: {rels}",
                    })
        return contradictions

    def to_dict(self) -> Dict[str, Any]:
        """Convert graph to a dictionary for export and serialization."""
        return {
            "events": [ev.to_dict() for ev in self._events.values()],
            "edges": [e.to_dict() for e in self.get_all_edges()],
        }

    def to_dot(self) -> str:
        """Export graph to Graphviz DOT format."""
        lines = ["digraph TemporalGraph {", '  rankdir="LR";', '  node [shape="box", style="rounded"];']
        for ev in self._events.values():
            label = f"{ev.event_id}\\n({ev.description})"
            lines.append(f'  "{ev.event_id}" [label="{label}"];')
        for edge in self.get_all_edges():
            style = 'dashed, color="blue"' if edge.is_inferred else 'solid, color="black"'
            lines.append(
                f'  "{edge.source_id}" -> "{edge.target_id}" [label="{edge.relation.value}", style={style}];'
            )
        lines.append("}")
        return "\n".join(lines)
