"""One-off helper (not part of the permanent scripts/ toolkit) used to apply
the thread-attribution leakage remediation (docs/hypothesis_expansion_and_
leakage_remediation_plan.md, Part 2) to the 5 pilot stories.

Usage: define EDITS as {story_dir: {event_id: new_text}} and run. Since the
replacement texts are pronoun/description-based (no character name), the
same text is valid for both original.json and counterfactual.json -- the
name-bearing alternative only exists in the events we deliberately leave
unchanged. linear.json is regenerated by copying the (possibly updated)
original text across its id_map_from_original.
"""

import json
import os

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
STORIES_DIR = os.path.join(ROOT, "data", "stories")


def load(story_dir, variant):
    path = os.path.join(STORIES_DIR, story_dir, f"{variant}.json")
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def save(story_dir, variant, data):
    path = os.path.join(STORIES_DIR, story_dir, f"{variant}.json")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write("\n")


def apply_edits(story_dir, edits):
    original = load(story_dir, "original")
    counterfactual = load(story_dir, "counterfactual")
    linear = load(story_dir, "linear")

    for event in original["events"]:
        if event["id"] in edits:
            event["text"] = edits[event["id"]]
    for event in counterfactual["events"]:
        if event["id"] in edits:
            event["text"] = edits[event["id"]]

    id_map = linear["id_map_from_original"]
    text_by_orig_id = {e["id"]: e["text"] for e in original["events"]}
    for orig_id, lin_id in id_map.items():
        if orig_id in edits:
            for event in linear["events"]:
                if event["id"] == lin_id:
                    event["text"] = text_by_orig_id[orig_id]
                    break

    save(story_dir, "original", original)
    save(story_dir, "counterfactual", counterfactual)
    save(story_dir, "linear", linear)
    print(f"{story_dir}: applied {len(edits)} text edits across original/counterfactual/linear")


STORY_01_EDITS = {
    "s4": "He banks hard as a plane goes down below him, the fight barely a minute old.",
    "s5": "He watches the mole get bombed for the third time that week.",
    "s6": "He pulls a shivering pilot from the water, radio crackling with news from the beach.",
    "s7": "Gliding now with the engine cut, he sees hundreds of men lined up on the sand below.",
    "s11": "He crosses the channel at altitude, smoke already rising from the coastline ahead.",
    "s13": "He watches the coastline rise fast, the crowded sand now filling the whole of his windscreen.",
    "s14": "The pilot braces in the cockpit as the sea rushes up grey and flat beneath him.",
    "s16": "He is hauled, dripping, over the gunwale of a small fishing boat, the whole ordeal over almost as soon as it began.",
    "s17": "He queues at the water's edge for hours, watching ship after ship turn back under strafing fire.",
    "s18": "He shares a tin of rations with a stranger, both of them trading rumors of a mole further down the beach.",
    "s20": "He watches a destroyer go down just offshore, the tide afterward pushing wreckage back onto the sand.",
    "s22": "He is given a place near the front of the queue as darkness falls.",
    "s24": "He steers around a drifting lifeboat, empty and half-swamped in the swell.",
    "s25": "He spots the wreckage of a downed fighter bobbing in the water ahead.",
    "s28": "His boat joins a line of small craft ferrying men out to the larger ships, the work stretching on into the early afternoon.",
    "s29": "He takes on a dozen soldiers, the little boat riding low and the fuel gauge sinking toward empty.",
    "s34": "He hears of a destroyer lost just offshore and holds off telling the families waiting outside.",
}


STORY_02_EDITS = {
    "s1": "The inspector opens the arson case file on Monday morning.",
    "s3": "On Tuesday, he re-interviews the landlord about the building's history.",
    "s7": "By Wednesday, he learns the landlord filed an insurance claim the same week as the fire.",
    "s9": "He arrests Elena on Thursday, one day after learning of the claim.",
    "s11": "By Tuesday evening, he has the fire marshal's forensic report open on his desk.",
    "s27": "She pulled the car around to the back street to meet her.",
}

STORY_03_EDITS = {
    "s4": "He finds a witness who remembers the doorway.",
    "s7": "He corners the witness for a straight answer about the doorway.",
    "s11": "He finds a bloodstained cloth tucked behind a piling near the address.",
    "s12": "He bags the cloth himself and drives it to the forensic lab.",
    "s13": "He waits at the lab through the following hour for preliminary results.",
    "s14": "He gets confirmation from the lab and matches it to the arrest record Voss found.",
    "s6": "He cross-references the registry against a name Corvin radioed in.",
    "s9": "He matches the name to an arrest record and radios Corvin the address.",
    "s17": "He finds a neighbor who saw someone dispose of a bloodstained cloth near the scene.",
    "s18": "He sends word to the forensic lab to prioritize the cloth evidence.",
    "s19": "He reviews the lab's chain-of-custody paperwork while waiting on results.",
    "s20": "He receives the lab's confirmation and cross-checks it against the arrest record.",
}

STORY_04_EDITS = {
    "s5": "She edges the van forward from 10:12 to 10:25, the last stretch of the wait.",
    "s10": "She double-checks the side mirror in the first few minutes, from 9:58 to 10:05.",
    "s11": "From 10:03 she keeps her foot hovering over the clutch, all the way until the engine cuts out at 10:22.",
    "s12": "She cracks the window to listen at 10:10, sealing it again by 10:18.",
    "s13": "Her hand rests on the gearshift from 10:13 to 10:20, deep in the second stretch of waiting.",
    "s22": "She settles low against the parapet from 9:55 to 9:59, the very start of her watch.",
    "s23": "From 9:59 she keeps her scope trained on the street, until she climbs down at 10:10.",
    "s26": "At 10:15 she keys her radio open and holds the channel until 10:18.",
    "s27": "From 10:18 she gathers her gear, gone by 10:20.",
    "s30": "From 10:03 she counts her own heartbeat to stay calm, all the way until she's finally let up at 10:16.",
    "s32": "From 10:09 she listens to bags being filled, right up until she's allowed to stand at 10:16.",
    "s39": "From 10:12 he tracks the van's every inch of movement, all the way to 10:26.",
}

STORY_05_EDITS = {
    "s5": "Her shift includes a code blue at 9:30pm that resolves by 10:15pm.",
    "s8": "The overnight nurse's follow-up block starts at 2:00am and, like everyone else, wraps at 7:00am.",
    "s6": "He actually begins an equipment check at 7:00pm sharp, though his official patrol doesn't start until 9:00pm.",
    "s26": "His mid-shift break, 10:00pm-10:15pm, is swallowed entirely within the perimeter sweep.",
}


if __name__ == "__main__":
    apply_edits("story_01", STORY_01_EDITS)
    apply_edits("story_02", STORY_02_EDITS)
    apply_edits("story_03", STORY_03_EDITS)
    apply_edits("story_04", STORY_04_EDITS)
    apply_edits("story_05", STORY_05_EDITS)
